### PR TITLE
Big changes - please review - Fixes #4, #15, #20

### LINKED ISSUE #4: extract plain text files from ALTO XML

### LINKED ISSUE #15: convert to a command-line program
maybe the easiest way to do this will be to fork GITenberg and replay our changes to it.

### LINKED ISSUE #20: Delete data directory and move data2 to data
Am I correct in assuming that the original `data` subdirectory is obsolete and the `data2` directory matches (or is closer to) the format of the data from the BL?

I'm happy to do the work, just want to make sure I'm understanding things correctly.

### PR DESCRIPTION
**Pull request by tfmorris**
Although I've got commit privileges to the repo and I think all this stuff is fine, there are some relatively large changes in here, so I'm posting it as a pull request for folks to review.  I've created three test repos with this code e.g. https://github.com/Git-Lit/000000206

Enhancements:
- Added an Alto XML parser which generates quality scores, page & word counts, raw text - addresses #4 & #10
- Changed templates to: 1) refer to this organization instead of Jon's person account, 2) include links to BL & Flickr, 3) be more aesthetically pleasing, at least to me, but they still need more work
- Added support to work directly from zip files so that they don't need to be unpacked.

Data reorganization
- deleted `data` subdirectory with old format examples and renamed `data2` to `data` - fixes #20
- deleted most unzipped XML files (a few were left as examples)

Code cleanup
- deleted all redundant code
- removed all unused imports
- fixed all errors/warnings (except for the problematic `sh` module)
- tested and verified from the command line - fixes #15 
- ignore a bunch of files (.pyc, Eclipse project files, etc)

### CODE REVIEW

**Comment by tfmorris** [comment]
Added some basic paragraph detection.  For the basic text format, we'll either have to sacrifice page markers (which aren't aligned with some logical block like a chapter) or forgo being able to join paragraphs/lines across page boundaries.

I did some hand editing to the repo at https://github.com/Git-Lit/000000206 to experiment with the way things should look.  Feel free to do the same and use your experimentation to open new issues in this repo.

**Comment by tfmorris** [comment]
The best way to get a feel for how the paragraph detection works is to look at https://github.com/Git-Lit/000000216/blob/master/000000216.md  I hand edited out some of the page markers, but other than that, it's basically true.  One remaining issue is cross page paragraph (and hyphenation) breaks.

**Comment by JonathanReeve** [comment]
This is so awesome! I'm super excited about the ALTO parsing, especially. I'll merge this now, and play around it with it in greater detail as soon as I can.

**Comment by tfmorris** [comment]
Thanks Jon.  I've got a few more changes in the pipe, including the
beginnings of ASCIIDOC output (as you can see from some of the recently
created repo), but am quickly running out of the easy stuff. :-)

Here's one of the ASCIIDOC examples, as rendered by Github:
https://github.com/Git-Lit/000000037/blob/master/000000037.adoc#chapter-iii

More example docs would be useful if you get a chance to load them, because
we're quickly getting into the area of things that vary among volumes e.g.
identification of chapters, signatures, etc.

What are you thinking about project communication channels? We can continue
to rely on the issue tracker & wiki, but it feels like an additional
channel for more free-form communication might be useful.

**Pull request merged**
